"""empty message

Revision ID: 0ef8804846e5
Revises: 
Create Date: 2020-04-28 01:38:51.441005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef8804846e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('administrator',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('regular',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('age', sa.String(length=50), nullable=True),
    sa.Column('height', sa.String(length=50), nullable=True),
    sa.Column('leadership', sa.String(length=30), nullable=True),
    sa.Column('ethnicity', sa.String(length=30), nullable=True),
    sa.Column('personality', sa.String(length=30), nullable=True),
    sa.Column('education', sa.String(length=50), nullable=True),
    sa.Column('hobby', sa.String(length=50), nullable=True),
    sa.Column('faculty', sa.String(length=50), nullable=True),
    sa.Column('occupation', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('Sets',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('set_name', sa.String(length=20), nullable=True),
    sa.Column('purpose', sa.String(length=30), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('administrator', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrator'], ['administrator.user_id'], ),
    sa.PrimaryKeyConstraint('sid'),
    sa.UniqueConstraint('set_name')
    )
    op.create_table('userScore',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.DECIMAL(precision=2, scale=1), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['regular.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'feature')
    )
    op.create_table('SetUserGp',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('gp_num', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sid'], ['Sets.sid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['regular.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'sid', 'gp_num')
    )
    op.create_table('joinSet',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sid'], ['Sets.sid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['regular.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'sid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('joinSet')
    op.drop_table('SetUserGp')
    op.drop_table('userScore')
    op.drop_table('Sets')
    op.drop_table('regular')
    op.drop_table('administrator')
    op.drop_table('user')
    # ### end Alembic commands ###
